name: Test pull request
on:
  pull_request:
    paths:
      - '**/*.ts'
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: List Directories and files
        run: ls -la 