name: Learn Github Actions
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker version
        run: docker version

      - name: build image
        run: docker build -t gemyero/redis .
      