name: Learn Github Actions
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v12.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.17

      - name: node version
        run: node --version
